export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const GET_ERROR = 'GET_ERROR' 
export const CLEAR_ERROR = 'CLEAR_ERROR'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'

export const UPDATE_USER_ROLE_SUCCESS = 'UPDATE_USER_ROLE_SUCCESS'
export const UPDATE_USER_ROLE_FAIL = 'UPDATE_USER_ROLE_FAIL'

export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_SUCCESS =' UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL'

export const PRODUCT_LOADING = 'PRODUCT_LOADING'
export const PRODUCT_LOADED = 'PRODUCT_LOADED'

export const ALL_PRODUCT_LOADING = 'ALL_PRODUCT_LOADING'
export const ALL_PRODUCT_LOADED = 'ALL_PRODUCT_LOADED'

export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL'

export const REVIEW_PRODUCT_SUCCESS = 'REVIEW_PRODUCT_SUCCESS'
export const REVIEW_PRODUCT_FAIL = 'REVIEW_PRODUCT_FAIL'
export const REVIEW_PRODUCT_LOADING = 'REVIEW_PRODUCT_LOADING'

export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'

export const ADD_CART_ITEM = 'ADD_CART_ITEM'
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'
export const CLEAR_CART_ITEMS = 'CLEAR_CART_ITEMS'
export const FETCH_CART_ITEM = 'FETCH_CART_ITEM'
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD ='CART_SAVE_PAYMENT_METHOD'

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'
export const CREATE_ORDER_RESET = 'CREATE_ORDER_RESET'

export const FETCH_ORDER_DETAIL_REQUEST = 'FETCH_ORDER_DETAIL_REQUEST'
export const FETCH_ORDER_DETAIL_SUCCESS = 'FETCH_ORDER_DETAIL_SUCCESS'

export const ORDER_DETAILS_FAIL = ' ORDER_DETAILS_FAIL'
export const ORDER_DETAILS_REQUEST = ' ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = ' ORDER_DETAILS_SUCCESS'
export const LIST_ORDER_REQUEST = 'LIST_ORDER_REQUEST'
export const LIST_ORDER_SUCCESS = "LIST_ORDER_SUCCESS"
export const LIST_ORDER_FAIL = 'LIST_ORDER_FAIL'
export const MY_LIST_ORDER_REQUEST = 'MY_LIST_ORDER_REQUEST'
export const MY_LIST_ORDER_SUCCESS = "MY_LIST_ORDER_SUCCESS"
export const MY_LIST_ORDER_FAIL = 'MY_LIST_ORDER_FAIL'



